apiVersion: apps/v1
kind: Deployment
metadata:
  name: cineverse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cineverse
  template:
    metadata:
      labels:
        app: cineverse
    spec:
      containers:
      - name: cineverse
        image: daniyaalabbas/cineverse:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: cineverse-service
spec:
  selector:
    app: cineverse
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081
  type: NodePort
